module.exports.Roles = {
  CLIENTE: 'CLIENTE',
  PROFECIONAL: 'PROFECIONAL',
  ADMIN: 'ADMIN',
}

module.exports.Estados = {
  PENDIENTE_CONFIRMACION: 'PENDIENTE_CONFIRMACION',
  PENDIENTE_REALIZACION: 'PENDIENTE_REALIZACION',
  CANCELADA: 'CANCELADA',
  EN_PROGRESO: 'EN_PROGRESO',
  TERMINADA: 'TERMINADA',
}

module.exports.TipoTrabajo = {
  PUBLICO: 'PUBLICO',
  PRIVADO: 'PRIVADO',
}
